name = "GraphPlayground"
uuid = "2f75e71a-fce0-4c28-bcf9-dfff7d3cf56c"
authors = ["David Gleich <dgleich@purdue.edu> and contributors"]
version = "0.1.0"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
GraphMakie = "1ecd5474-83a3-4783-bb4f-06765db800d2"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
GraphMakie = "0.5"
julia = "1.10"
